## NUMPY TAREA 1

In [1]:
import numpy as np

In [2]:
import os

In [3]:
z = [1,2,3,4,5]

In [4]:
w = 2*z
w

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
x = [6,5,4,3,2,1]

In [6]:
r = w + x
r

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]

In [7]:
a = [1,3,5,7,9]

In [8]:
print(a[2:4])

[5, 7]


In [9]:
b = ([1,3,5,9],[2,4,6,8,10])

In [10]:
print(b[0])

[1, 3, 5, 9]


In [11]:
print(b[1][2:4])

[6, 8]


In [12]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [13]:
a

array([1, 2, 3, 4, 5, 6])

In [14]:
c = 2*a

In [15]:
print (c)

[ 2  4  6  8 10 12]


In [16]:
type(c)

numpy.ndarray

In [17]:
c.shape

(6,)

In [18]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list

In [19]:
a = np.array(l) # convert a list to an array

In [20]:
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [21]:
a.shape

(3, 3)

In [22]:
print(a.dtype)

int64


In [23]:
M = np.array([[1, 2], [3, 4]])

In [24]:
M.shape

(2, 2)

In [25]:
M.dtype

dtype('int64')

In [26]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [27]:
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [28]:
print(a[0])

[1 2 3]


In [29]:
print(a[1, 2]) # arrays can be given comma separated indices

9


In [30]:
print(a[1, 1:3])

[6 9]


In [31]:
print(a[:,1])

[2 6 4]


In [32]:
a[1, 2] = 7

In [33]:
print(a)


[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [34]:
a[:, 0] = [0, 9, 8]

In [35]:
print(a)


[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [36]:
x = np.arange(0, 10, 1)

In [37]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [38]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [39]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [41]:
b.dtype

dtype('float64')

In [42]:
n = 1000


In [43]:
np.int = int

In [44]:
my_int_array = np.zeros(n, dtype=np.int)

In [45]:
my_int_array.dtype

dtype('int64')

In [46]:
c = np.ones((3,3))


In [47]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
d = np.arange(5) # just like range()

In [49]:
print(d)

[0 1 2 3 4]


In [50]:
d[1] = 9.7

In [51]:
print(d) # arrays keep their type even if elements changed

[0 9 2 3 4]


In [52]:
print(d*0.4) # operations create a new array, with new type

[0.  3.6 0.8 1.2 1.6]


In [53]:
np.float = float

In [54]:
d = [np.arange(5, dtype=np.float)]

In [55]:
print(d)


[array([0., 1., 2., 3., 4.])]


In [56]:
np.arange(3, 7, 0.5) # arbitrary start, stop and step

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [57]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [58]:
# random data
np.random.rand(5,5)

array([[0.46167105, 0.75937104, 0.4506995 , 0.18813977, 0.68568826],
       [0.33615097, 0.59897978, 0.32372519, 0.63227017, 0.29563947],
       [0.20020308, 0.16981258, 0.02445373, 0.03499307, 0.14178206],
       [0.86951929, 0.09357476, 0.56839065, 0.48181655, 0.6939533 ],
       [0.2507128 , 0.55632965, 0.6981654 , 0.21101946, 0.3709003 ]])

In [59]:
os.system('head DeBilt.txt')

1

In [60]:
data = np.genfromtxt('DeBilt.txt'),

FileNotFoundError: DeBilt.txt not found.

In [61]:
np.savetxt('datasaved.txt', data)

In [62]:
os.system('head datasaved.txt')

1

In [63]:
M = np.random.rand(3,3)
M

array([[0.05726407, 0.43411655, 0.54677798],
       [0.79547999, 0.89609484, 0.7347316 ],
       [0.21007013, 0.64132365, 0.2865299 ]])

In [64]:
np.save('saved-matrix.npy', M)

In [65]:
np.load('saved-matrix.npy')

array([[0.05726407, 0.43411655, 0.54677798],
       [0.79547999, 0.89609484, 0.7347316 ],
       [0.21007013, 0.64132365, 0.2865299 ]])

In [66]:
a = np.arange(4.0)


In [67]:
b = a * 23.4
c = b/(a+1)
c += 10
print (c)

[10.   21.7  25.6  27.55]


In [68]:
arr = np.arange(100, 200)

In [69]:
select = [5, 25, 50, 75, -5]

In [70]:
print(arr[select]) # can use integer lists as indices

[105 125 150 175 195]


In [71]:
arr = np.arange(10, 20).reshape((2,5))

In [72]:
arr.sum()

np.int64(145)

In [73]:
arr.mean()

np.float64(14.5)

In [74]:
arr.std()

np.float64(2.8722813232690143)

In [75]:
arr.max()

np.int64(19)

In [76]:
arr.min()

np.int64(10)

In [77]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])

In [78]:
arr.sort() # acts on array itself
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [79]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [80]:
print(x)

[4.5 2.3 6.7 1.2 1.8 5.5]


In [81]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])

In [82]:
print (a)

[[1. 2.]
 [4. 3.]]


In [83]:
a.transpose()

array([[1., 4.],
       [2., 3.]])

In [84]:
A = np.array([[1, 2], [3, 4]])  # Example matrix
A_inv = np.linalg.inv(A)  # Compute the inverse
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [85]:
u = np.eye(2)  # 2x2 identity matrix
print(u)

[[1. 0.]
 [0. 1.]]


In [86]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [87]:
np.dot (j, j) # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [88]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b

array([6., 4., 9.])

In [89]:
a - b

array([-4.,  0., -3.])

In [90]:
a * b

array([ 5.,  4., 18.])

In [91]:
b / a

array([5., 1., 2.])

In [92]:
a % b

array([1., 0., 3.])

In [93]:
b**a

array([  5.,   4., 216.])

In [94]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [95]:
b

array([-1.,  3.])

In [96]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [97]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [98]:
a * a

array([[ 1.,  4.],
       [ 9., 16.],
       [25., 36.]])

In [99]:
b * b

array([1., 9.])

In [100]:
a * b

array([[-1.,  6.],
       [-3., 12.],
       [-5., 18.]])