In [1]:
a = [1,3,5,7,9]
print(a[2:4])
b = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
print(b[0])
print(b[1][2:4])


[5, 7]
[1, 3, 5, 7, 9]
[6, 8]


In [3]:
a = [1,3,5,7,9]
b = [3,5,6,7,9]
c = a + b
print(c)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


In [4]:
import numpy as np

In [6]:
# as vectors from lists
a = np.array([1,3,5,7,9])
b = np.array([3,5,6,7,9])
c = a + b
print(c)

c.shape

[ 4  8 11 14 18]


(5,)

In [7]:
type(c)

numpy.ndarray

In [14]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list
a = np.array(l) # convert a list to an array
print(a)

a.shape

print(a.dtype) # get type of an array

# or directly as matrix
M = np.array([[1, 2], [3, 4]])
M.shape
M.dtype


[[1 2 3]
 [3 6 9]
 [2 4 6]]
int64


dtype('int64')

In [15]:
M[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

In [17]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
a

array([[1, 2, 3],
       [3, 6, 9],
       [2, 4, 6]])

In [19]:
print(a[0])

[1 2 3]


In [20]:
print(a[1, 2])

9


In [21]:
print(a[1, 1:3])

[6 9]


In [22]:
print(a[:,1])

[2 6 4]


In [23]:
a[1, 2] = 7
print(a)

[[1 2 3]
 [3 6 7]
 [2 4 6]]


In [24]:
a[:, 0] = [0, 9, 8]
print(a)

[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [29]:
x = np.arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [32]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [33]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [35]:
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [36]:
b.dtype

dtype('float64')

In [37]:
n = 1000

In [41]:
my_int_array = np.zeros(n, dtype=int)
my_int_array.dtype

dtype('int64')

In [42]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
d = np.arange(5) # just like range()
print(d)

d[1] = 9.7
print(d) # arrays keep their type even if elements changed

print(d*0.4) # operations create a new array, with new type

d = np.arange(5, dtype=np.float)
print(d)

np.arange(3, 7, 0.5) # arbitrary start, stop and step
np.array([ 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

[0 1 2 3 4]
[0 9 2 3 4]
[0.  3.6 0.8 1.2 1.6]


AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [44]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x
np.array([[0, 0, 0, 0, 0],
[1, 1, 1, 1, 1],
[2, 2, 2, 2, 2],
[3, 3, 3, 3, 3],
[4, 4, 4, 4, 4]])
# random data
np.random.rand(5,5)

array([[0.37140954, 0.51990702, 0.81554837, 0.95082422, 0.60557914],
       [0.20913974, 0.96942407, 0.40412186, 0.66077925, 0.76346187],
       [0.34140171, 0.6920806 , 0.48207836, 0.58437386, 0.47763863],
       [0.93947761, 0.33668785, 0.99142044, 0.40399746, 0.8132307 ],
       [0.44136248, 0.28639113, 0.69729868, 0.43747335, 0.83734707]])

In [45]:
M = np.random.rand(3,3)

In [46]:
M

array([[0.84075044, 0.97121694, 0.34591488],
       [0.41882705, 0.76657938, 0.5376624 ],
       [0.41173454, 0.76709039, 0.85031831]])

In [47]:
np.save('saved-matrix.npy', M)

In [48]:
np.load('saved-matrix.npy')

array([[0.84075044, 0.97121694, 0.34591488],
       [0.41882705, 0.76657938, 0.5376624 ],
       [0.41173454, 0.76709039, 0.85031831]])

In [50]:
a = np.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10
print(c)

[10.   21.7  25.6  27.55]


In [51]:
a = np.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10
print(c)

arr = np.arange(100, 200)
select = [5, 25, 50, 75, -5]
print(arr[select]) # can use integer lists as indices

[10.   21.7  25.6  27.55]
[105 125 150 175 195]


In [52]:
arr = np.arange(10, 20).reshape((2,5))

In [54]:
arr.sum()

arr.mean()

arr.std()

arr.max()

arr.min()

np.int64(10)

In [55]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
arr.sort() # acts on array itself
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [56]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [57]:
print(x)

[4.5 2.3 6.7 1.2 1.8 5.5]


In [61]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])
print(a)

a.transpose()
np.array([[ 1., 3.],
[ 2., 4.]])
np.linalg.inv(a)
np.array([[-2. , 1. ],
[ 1.5, -0.5]])
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u
np.array([[ 1., 0.],
[ 0., 1.]])
j = np.array([[0.0, -1.0], [1.0, 0.0]])
np.dot(j, j) # matrix product

[[1. 2.]
 [4. 3.]]


array([[-1.,  0.],
       [ 0., -1.]])

In [63]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b
np.array([6., 4., 9.])
a - b
np.array([-4., 0., -3.])
a * b
np.array([5., 4., 18.])
b / a
np.array([5., 1., 2.])
a % b
np.array([1., 0., 3.])
b**a
np.array([5., 4., 216.])
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a
np.array([[ 1., 2.],
[ 3., 4.],
[ 5., 6.]])
b
np.array([-1., 3.])
a + b
np.array([[ 0., 5.],
[ 2., 7.],
[ 4., 9.]])

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [64]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a * a
np.array([[ 1., 4.],
[ 9., 16.],
[ 25., 36.]])
b * b
np.array([ 1., 9.])
a * b
np.array([[ -1., 6.],
[ -3., 12.],
[ -5., 18.]])

array([[-1.,  6.],
       [-3., 12.],
       [-5., 18.]])